### ISSUE TITLE
using vue router 

### ISSUE THREAD

**Issue by srmb11** [ilikerobots/django-vue-mpa#1]
I tried to use router but it's not working 
here is the thing that I did :

1. install router 
    `npm install vue-router`

2. create src/router directory and explicitly install the router via Vue.use()  in router/index.js
```
import Vue from 'vue'
import Router from 'vue-router'
import HelloWorld from '@/components/HelloWorld.vue'

Vue.use(Router)

export default new Router({
  routes: [
    {
      path: '/vue_app_01/',
      name: 'HelloWorld',
      component: HelloWorld
    },     
  ]
})
```
3.  add router instance to main.js , this is how new main.js looks like
```
import Vue from 'vue'
import App from './App.vue'
import router from './router'



Vue.config.productionTip = false

new Vue({
  render: h => h(App),
  router,
}).$mount('#app')
```
4. in App.vue changed the explicit call for HelloWorld component to router-view
```
<template>
  <div id="app">
    <img alt="Vue logo" src="./assets/logo.png">
        <router-view/>
  </div>
</template>

<script>

export default {
  name: 'app',
  components: {
  }
}
</script>

<style>
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
```
after this the vue_app_01 still works but the HelloWorld component doesnt load on the page

**Comment by srmb11** [comment]
I did a little digging, logged  `this.$route` to the console, and I found out that router path is always equal to root `/` 
now I have doubt that even routing is possible with django-webpack-loader

**Comment by robertpro** [comment]
@srmb11 I don't think vue router is going to work, since this example is using routes from Django not Vue, actually I think is the expected behaviour

**Comment by ilikerobots** [comment]
@robertpro is correct. I don't see any way Vue routing would work in this context (mpa). Possibly routing could work within a single entry point, but I'm not sure what the use case for that would be.  I think there are better ways to preserve location histories if that's the goal.
